SFLAGS += -Iomg/include

omg_src += $(addprefix omg/src/,\
  arithmetic.cpp \
  float.cpp \
  list.cpp \
  memory.cpp \
  print.cpp \
  directions.cpp \
  unicode_helper.cpp \
)

tests_src += $(addprefix omg/test/,\
  bit_helper.cpp\
  print.cpp\
  signaling_nan.cpp\
)

omg_bench_src = $(addprefix omg/src/,\
  print.cpp \
)
