.SUFFIXES:

.SECONDARY:

.SECONDEXPANSION:

include src/config.mak
include src/toolchain.mak

include src/helpers.mak
include src/flavor.mak

include src/goal.mak
include src/module.mak

include src/rules.mak
