.SUFFIXES:

.SECONDARY:

.SECONDEXPANSION:

PATH_haussmann ?= .

include $(PATH_haussmann)/src/config.mak
include $(PATH_haussmann)/src/toolchain.mak

include $(PATH_haussmann)/src/helpers.mak
include $(PATH_haussmann)/src/flavor.mak

include $(PATH_haussmann)/src/goal.mak
include $(PATH_haussmann)/src/module.mak

include $(PATH_haussmann)/src/rules.mak
